## Installing necessary packages

In [2]:
! pip install biopython

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.2/3.2 MB 42.9 MB/s eta 0:00:00


In [3]:
! pip install -q condacolab

In [ ]:
import condacolab
condacolab.install()

⏬ Downloading https://github.com/jaimergp/miniforge/releases/download/24.11.2-1_colab/Miniforge3-colab-24.11.2-1_colab-Linux-x86_64.sh...
📦 Installing...
📌 Adjusting configuration...
🩹 Patching environment...
⏲ Done in 0:00:16
🔁 Restarting kernel...


In [4]:
! conda install -c bioconda seqkit

/bin/bash: line 1: conda: command not found


## Biopython

## Working with PDB

In [1]:
from Bio.PDB import *

ModuleNotFoundError: No module named 'Bio'

In [ ]:
# load PBD structure
pdbl = PDBList()
pdbl.retrieve_pdb_file('1GCN', pdir = '.', file_format = 'pdb')

Structure exists: './pdb1gcn.ent' 


'./pdb1gcn.ent'

In [ ]:
pdb_file = 'pdb1gcn.ent'

# create a parser
p = PDBParser(QUIET=True)

# parse various structure parts
structure = p.get_structure('protein', pdb_file)
model = structure[0]
chain = model['A']

The Structure object follows the so-called SMCRA (Structure/Model/Chain/Residue/Atom) architecture :

* A structure consists of models (crystal structures generally have only one model (with id 0), while NMR files usually have several models)
* A model consists of chains
* A chain consists of residues
* A residue consists of atoms

![picture](https://drive.google.com/uc?export=view&id=1KbDCusv26kT0Xb9IX2bzI5PC2eBUNYZm)



In [ ]:
print(structure)
print(model)
print(chain)

<Structure id=protein>
<Model id=0>
<Chain id=A>


In [ ]:
# get atoms
atom_struct = structure.get_atoms()

atom_struct # <- this means we need to unpack this object

<generator object Structure.get_atoms at 0x7fa1215d7b90>

In [ ]:
# make a list an show first 10 elements
atom_lst = list(atom_struct)
print(len(atom_lst))
print(atom_lst[:10])

246
[<Atom N>, <Atom CA>, <Atom C>, <Atom O>, <Atom CB>, <Atom CG>, <Atom ND1>, <Atom CD2>, <Atom CE1>, <Atom NE2>]


In [ ]:
# show coordinates for first 10 atoms
for atom in atom_lst[:10]:
    print(atom.get_coord())

[49.668 24.248 10.436]
[50.197 25.578 10.784]
[49.169 26.701 10.917]
[48.241 26.524 11.749]
[51.312 26.048  9.843]
[50.958 26.068  8.34 ]
[49.636 26.144  7.86 ]
[51.797 26.043  7.286]
[49.691 26.152  6.454]
[51.046 26.09   6.098]


In [ ]:
# get residues
residues = structure.get_residues()
residues

<generator object Structure.get_residues at 0x7fa1215d6e90>

In [ ]:
# make a list an show first 10 elements
res_lst = list(residues)
print(len(res_lst))
print(res_lst[:10])

29
[<Residue HIS het=  resseq=1 icode= >, <Residue SER het=  resseq=2 icode= >, <Residue GLN het=  resseq=3 icode= >, <Residue GLY het=  resseq=4 icode= >, <Residue THR het=  resseq=5 icode= >, <Residue PHE het=  resseq=6 icode= >, <Residue THR het=  resseq=7 icode= >, <Residue SER het=  resseq=8 icode= >, <Residue ASP het=  resseq=9 icode= >, <Residue TYR het=  resseq=10 icode= >]


In [ ]:
# extracting specific parts
residue = chain[20]
atom = residue["CA"]

print(residue)
print(atom)

<Residue GLN het=  resseq=20 icode= >
<Atom CA>


In [ ]:
# get residue properties

print(residue.get_resname()) # return the residue name (eg. 'GLY')
print(residue.is_disordered()) # 1 if the residue has disordered atoms
print(residue.get_segid()) # return the SEGID
print(residue.has_id("CA")) # test if a residue has a certain atom
print(residue.has_id("S"))

GLN
0
    
True
False


In [ ]:
# get atom properties

print(atom.get_name())  # atom name (spaces stripped, e.g. 'CA')
print(atom.get_id())  # id (equals atom name)
print(atom.get_coord())  # atomic coordinates
print(atom.get_vector())  # atomic coordinates as Vector object
print(atom.get_fullname())  # atom name (with spaces, e.g. '.CA.')

CA
CA
[17.013 19.632 12.689]
<Vector 17.01, 19.63, 12.69>
 CA 


In [ ]:
# simple calculations

at1 = residue["CA"]
at2 = residue["CD"]
at3 = residue["N"]

vector1 = at1.get_vector()
vector2 = at2.get_vector()
vector3 = at3.get_vector()

distance = at1 - at2
angle = calc_angle(vector1, vector2, vector3)

print(distance)
print(angle)

3.8060117
0.21054893652989898


### Working with FASTA

In [ ]:
from Bio import SeqIO

In [ ]:
filename='test_file.fasta'
ext = 'fasta'

sequences = SeqIO.parse(filename, ext) # seq input; returns an iterator
sequences

In [ ]:
for seq in sequences:
  print(seq)

ID: sp|P11473|VDR_HUMAN
Name: sp|P11473|VDR_HUMAN
Description: sp|P11473|VDR_HUMAN Vitamin D3 receptor OS=Homo sapiens OX=9606 GN=VDR PE=1 SV=1
Number of features: 0
Seq('MEAMAASTSLPDPGDFDRNVPRICGVCGDRATGFHFNAMTCEGCKGFFRRSMKR...EIS')
ID: 1GCN_1|Chain
Name: 1GCN_1|Chain
Description: 1GCN_1|Chain A|GLUCAGON|Sus scrofa (9823)
Number of features: 0
Seq('HSQGTFTSDYSKYLDSRRAQDFVQWLMNT')


In [ ]:
sequences = SeqIO.parse(filename, ext)
seq1 = next(sequences)

In [ ]:
print(seq1.id) # symbols before first whitespace
print(seq1.name) # same
print(seq1.description) # definition line
print(seq1.seq) # sequence line

sp|P11473|VDR_HUMAN
sp|P11473|VDR_HUMAN
sp|P11473|VDR_HUMAN Vitamin D3 receptor OS=Homo sapiens OX=9606 GN=VDR PE=1 SV=1
MEAMAASTSLPDPGDFDRNVPRICGVCGDRATGFHFNAMTCEGCKGFFRRSMKRKALFTCPFNGDCRITKDNRRHCQACRLKRCVDIGMMKEFILTDEEVQRKREMILKRKEEEALKDSLRPKLSEEQQRIIAILLDAHHKTYDPTYSDFCQFRPPVRVNDGGGSHPSRPNSRHTPSFSGDSSSSCSDHCITSSDMMDSSSFSNLDLSEEDSDDPSVTLELSQLSMLPHLADLVSYSIQKVIGFAKMIPGFRDLTSEDQIVLLKSSAIEVIMLRSNESFTMDDMSWTCGNQDYKYRVSDVTKAGHSLELIEPLIKFQVGLKKLNLHEEEHVLLMAICIVSPDRPGVQDAALIEAIQDRLSNTLQTYIRCRHPPPGSHLLYAKMIQKLADLRSLNEEHSKQYRCLSFQPECSMKLTPLVLEVFGNEIS


## SeqKit

In [ ]:
import subprocess

In [ ]:
incorrect_path = 'somefile.fasta'
seqkit = subprocess.run(("seqkit", "stats", incorrect_path, "-a"),
                            capture_output=True, # When set to True, will capture the standard output and standard error
                            text=True) # When set to True, will return the stdout and stderr as string, otherwise as bytes

In [ ]:
seqkit.stdout

''

In [ ]:
seqkit.stderr

'\x1b[ERRO]\x1b stat somefile.fasta: no such file or directory\n'

In [ ]:
correct_path = 'test_file.fasta'
seqkit = subprocess.run(("seqkit", "stats", correct_path, "-a"),
                            capture_output=True, text=True)

In [ ]:
seqkit

CompletedProcess(args=('seqkit', 'stats', 'test_file.fasta', '-a'), returncode=0, stdout='file             format  type     num_seqs  sum_len  min_len  avg_len  max_len  Q1   Q2   Q3  sum_gap  N50  N50_num  Q20(%)  Q30(%)  AvgQual  GC(%)  sum_n\ntest_file.fasta  FASTA   Protein         2      456       29      228      427  29  228  427        0  427        1       0       0        0      0      0\n', stderr='')

In [ ]:
seqkit.stderr

''

In [ ]:
seqkit.stdout

'file             format  type     num_seqs  sum_len  min_len  avg_len  max_len  Q1   Q2   Q3  sum_gap  N50  N50_num  Q20(%)  Q30(%)  AvgQual  GC(%)  sum_n\ntest_file.fasta  FASTA   Protein         2      456       29      228      427  29  228  427        0  427        1       0       0        0      0      0\n'

In [ ]:
# processing the results from stdout

seqkit_out = seqkit.stdout.strip().split('\n')

# split names and values
prop_names = seqkit_out[0].split()[1:]
prop_vals = seqkit_out[1].split()[1:]

# using zip
seq_result = dict(zip(prop_names, prop_vals))

In [ ]:
seq_result

{'format': 'FASTA',
 'type': 'Protein',
 'num_seqs': '2',
 'sum_len': '456',
 'min_len': '29',
 'avg_len': '228',
 'max_len': '427',
 'Q1': '29',
 'Q2': '228',
 'Q3': '427',
 'sum_gap': '0',
 'N50': '427',
 'N50_num': '1',
 'Q20(%)': '0',
 'Q30(%)': '0',
 'AvgQual': '0',
 'GC(%)': '0',
 'sum_n': '0'}